/**
 * – Criando Variáveis
 * 
• Crie um programa que declare duas variáveis do tipo inteiro e exiba o resultado da
soma dessas variáveis.
• Crie um programa que declare uma variável do tipo string e exiba seu conteúdo na
tela.
• Crie um programa que declare uma variável do tipo booleano e atribua a ela o valor
"true". Em seguida, exiba o valor dessa variável na tela.
• Crie um programa que declare uma variável do tipo numérico e atribua a ela o valor
3.1415. Em seguida, exiba o valor dessa variável na tela. 
 */

/* Crie um programa que declare duas variáveis do tipo inteiro e exiba o resultado da
soma dessas variáveis.*/